name: sixam_mart_delivery
description: A new Flutter application.
publish_to: 'none' #
version: 1.1.2+18

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  shared_preferences: ^2.0.6
  connectivity: ^3.0.6
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^17.1.2
  path_provider: ^2.0.10
  url_strategy: ^0.2.0
  pin_code_fields: ^8.0.1
  http: ^1.2.1
  flutter_switch: ^0.3.2
  shimmer_animation: ^2.0.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.0.6
  url_launcher: ^6.1.7
  vibration: ^1.7.6
  image_picker: ^1.1.1
  disable_battery_optimization: ^1.1.0+1
  phone_number: ^2.1.0
  country_code_picker: ^3.0.0
#  location: ^4.4.0
  audioplayers: ^6.0.0
  flutter_html: ^3.0.0-alpha.5
  cached_network_image: ^3.3.0
  image_compression_flutter: ^1.0.4
  win32: ^5.5.1
  path: ^1.8.1
  http_parser: ^4.0.2
  intl: ^0.19.0
  flutter_callkit_incoming:
    #    path: packages/flutter_callkit_incoming-1.0.2-2
    git:
      url: https://github.com/hiennguyen92/flutter_callkit_incoming
      ref: 1.0.2+2
  flutter_launcher_icons: ^0.13.1
dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/Logo.jpg"
  web:
    generate: true
    image_path: "assets/image/Logo.jpg"
    background_color: "#ffffff"
    theme_color: "#ee4367"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/font/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/font/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/font/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/font/Tajawal-Black.ttf
          weight: 900