// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdmp43G2pk4-CRCEph6bsljpJKzXXK7bY',
    appId: '1:187788958576:web:4bc503925f6b5834544db5',
    messagingSenderId: '187788958576',
    projectId: 'qareeb-31d01',
    // authDomain: 'qareeb-31d01.firebaseapp.com',
    // storageBucket: 'qareeb-31d01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9XW8Ha8hxRG1SJONcJ7wzY5pQJpkR-Os',
    appId: '1:187788958576:android:39db1258287c5ca9544db5',
    messagingSenderId: '187788958576',
    projectId: 'qareeb-31d01',
    storageBucket: 'qareeb-31d01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUpdws6P9SOF_ZWYvDYW_gblus2DKoXCc',
    appId: '1:187788958576:ios:87035ddaff41773a544db5',
    messagingSenderId: '187788958576',
    projectId: 'qareeb-31d01',
    storageBucket: 'qareeb-31d01.appspot.com',
    androidClientId:
        '187788958576-7raa4s5vgqfkgdjt8htsfr67m9mjo4iu.apps.googleusercontent.com',
    iosClientId:
        '187788958576-dbv9mgb9o2p2aj6hsauvlhsq97vp1k7s.apps.googleusercontent.com',
    iosBundleId: 'com.qareeb.deliveryboy',
  );
}
